### ISSUE TITLE
DRM contents playback capability 

### ISSUE THREAD

**Issue by sarkrui** [Leoyzen/M920x-Hackintosh-EFI#7]
I'm thinking whether your build is able to play **DRM contents** such as **Apple TV+, Netflix, Amazon Prime**. I look forward to replacing my giant ATX build with this M920X. It's really nice to have dGPU on such a mini PC. Since I didn't test DRM content support, thereby I would like to please you to try adding `shikigva=80` in your boot-args. In case you don't have a Netflix account, I can share mine with you for testing. 

Private contacts via sark.rui@gmail.com

**Comment by ghost** [comment]
> I'm thinking whether your build is able to play **DRM contents** such as **Apple TV+, Netflix, Amazon Prime**. I look forward to replacing my giant ATX build with this M920X. It's really nice to have dGPU on such a mini PC. Since I didn't test DRM content support, thereby I would like to please you to try adding `shikigva=80` in your boot-args. In case you don't have a Netflix account, I can share mine with you for testing.
> 
> Private contacts via [sark.rui@gmail.com](mailto:sark.rui@gmail.com)

Yes, DRM works with on the M920x variant with a RX560 dGPU.
There are two versions of the M920x. One with a dGPU and one without.
For the dGPU:
Set BIOS to auto.  To enable both GPU and iGPU so that SMBIOS iMac 19,1 matches the config.
Add the iGPU as headless in the config
Then add the dGPU with the shikigva=80.
DRM is working on my build.  Tested with Netflix, Amazon prime and Apple TV app.

**Comment by sarkrui** [comment]
Thank you @BRAVO-TWO ! In short, it's a super compact Q370 build PC with a dGPU! I thought it might have the issue as the NUCi7HVK has, having a VEGA M dGPU but unable to play DRM contents).
